version: '3'
services:
 redbox:
  image: qcifengineering/redbox
  ports:
    - "9000:9000"
 acceptance:
    build: .
    image: mattredbox/acceptance-redbox-distro
    links:
      - redbox
    environment:
      - GEB_BUILD_LOCAL_BASE_URL=http://redbox:9000/redbox
      - SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY
      - SAUCE_USERNAME=$SAUCE_USERNAME